require:
- rubocop-rails

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false
